Import of version 0.53

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -426,6 +426,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
+ac_default_prefix=/usr
 # Factoring default headers for most tests.
 ac_includes_default="\
 #include <stdio.h>
@@ -1023,10 +1024,10 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-static[=PKGS]
+                          build static libraries [default=no]
   --enable-shared[=PKGS]
                           build shared libraries [default=yes]
-  --enable-static[=PKGS]
-                          build static libraries [default=yes]
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
@@ -1492,6 +1493,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 am__api_version="1.4"
 ac_aux_dir=
 for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
@@ -1687,7 +1689,7 @@ fi
 
 PACKAGE=alltray
 
-VERSION=0.52
+VERSION=0.53
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1787,6 +1789,7 @@ fi
           ac_config_headers="$ac_config_headers config.h"
 
           ac_config_commands="$ac_config_commands default-1"
+
 
 
 ac_ext=c
@@ -4031,29 +4034,6 @@ _ACEOF
 
 fi
 
-# Check whether --enable-shared or --disable-shared was given.
-if test "${enable_shared+set}" = set; then
-  enableval="$enable_shared"
-  p=${PACKAGE-default}
-    case $enableval in
-    yes) enable_shared=yes ;;
-    no) enable_shared=no ;;
-    *)
-      enable_shared=no
-      # Look at the argument we got.  We use all the common list separators.
-      lt_save_ifs="$IFS"; IFS="${IFS}$PATH_SEPARATOR,"
-      for pkg in $enableval; do
-	IFS="$lt_save_ifs"
-	if test "X$pkg" = "X$p"; then
-	  enable_shared=yes
-	fi
-      done
-      IFS="$lt_save_ifs"
-      ;;
-    esac
-else
-  enable_shared=yes
-fi;
 
 # Check whether --enable-static or --disable-static was given.
 if test "${enable_static+set}" = set; then
@@ -4076,7 +4056,32 @@ if test "${enable_static+set}" = set; then
       ;;
     esac
 else
-  enable_static=yes
+  enable_static=no
+fi;
+
+
+# Check whether --enable-shared or --disable-shared was given.
+if test "${enable_shared+set}" = set; then
+  enableval="$enable_shared"
+  p=${PACKAGE-default}
+    case $enableval in
+    yes) enable_shared=yes ;;
+    no) enable_shared=no ;;
+    *)
+      enable_shared=no
+      # Look at the argument we got.  We use all the common list separators.
+      lt_save_ifs="$IFS"; IFS="${IFS}$PATH_SEPARATOR,"
+      for pkg in $enableval; do
+	IFS="$lt_save_ifs"
+	if test "X$pkg" = "X$p"; then
+	  enable_shared=yes
+	fi
+      done
+      IFS="$lt_save_ifs"
+      ;;
+    esac
+else
+  enable_shared=yes
 fi;
 
 # Check whether --enable-fast-install or --disable-fast-install was given.
@@ -4614,7 +4619,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4617 "configure"' > conftest.$ac_ext
+  echo '#line 4622 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5669,7 +5674,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5672:" \
+echo "$as_me:5677:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6701,11 +6706,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6704: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6709: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6708: \$? = $ac_status" >&5
+   echo "$as_me:6713: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6934,11 +6939,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6937: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6942: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6941: \$? = $ac_status" >&5
+   echo "$as_me:6946: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6994,11 +6999,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7002: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7001: \$? = $ac_status" >&5
+   echo "$as_me:7006: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9182,7 +9187,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9185 "configure"
+#line 9190 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9280,7 +9285,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9283 "configure"
+#line 9288 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11457,11 +11462,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11460: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11465: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11464: \$? = $ac_status" >&5
+   echo "$as_me:11469: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11517,11 +11522,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11520: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11525: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11524: \$? = $ac_status" >&5
+   echo "$as_me:11529: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12886,7 +12891,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12889 "configure"
+#line 12894 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12984,7 +12989,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12987 "configure"
+#line 12992 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13811,11 +13816,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13814: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13819: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13818: \$? = $ac_status" >&5
+   echo "$as_me:13823: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13871,11 +13876,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13874: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13879: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13878: \$? = $ac_status" >&5
+   echo "$as_me:13883: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15916,11 +15921,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15919: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15924: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15923: \$? = $ac_status" >&5
+   echo "$as_me:15928: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16149,11 +16154,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16152: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16157: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16156: \$? = $ac_status" >&5
+   echo "$as_me:16161: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16209,11 +16214,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16212: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16217: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16216: \$? = $ac_status" >&5
+   echo "$as_me:16221: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18397,7 +18402,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18400 "configure"
+#line 18405 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18495,7 +18500,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18498 "configure"
+#line 18503 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19510,10 +19515,7 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
-# test for LD_PRELOAD functionality
-# written original by Tim Potter
-# found here:
-# http://lists.samba.org/archive/samba-technical/1998-November/thread.html#2646
+
 
 echo "$as_me:$LINENO: checking for working function preloading (LD_PRELOAD)" >&5
 echo $ECHO_N "checking for working function preloading (LD_PRELOAD)... $ECHO_C" >&6
@@ -19588,14 +19590,86 @@ LIBDIR=""
 if test x"$_HAVE_LD_PRELOAD" = x"yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_LD_PRELOAD
+#define HAVE_LD_PRELOAD 1
 _ACEOF
 
   LIBDIR="lib"
 
 fi
 
-pkg_modules="gtk+-2.0 >= 2.4.0 gdk-2.0 gdk-pixbuf-xlib-2.0"
+
+
+
+  echo "$as_me:$LINENO: checking for /proc/self/maps" >&5
+echo $ECHO_N "checking for /proc/self/maps... $ECHO_C" >&6
+if test "${ac_cv_file__proc_self_maps+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/proc/self/maps"; then
+  ac_cv_file__proc_self_maps=yes
+else
+  ac_cv_file__proc_self_maps=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__proc_self_maps" >&5
+echo "${ECHO_T}$ac_cv_file__proc_self_maps" >&6
+
+  echo "$as_me:$LINENO: checking whether everything is installed to the same prefix" >&5
+echo $ECHO_N "checking whether everything is installed to the same prefix... $ECHO_C" >&6
+if test "${br_cv_valid_prefixes+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    if test "$bindir" = '${exec_prefix}/bin' -a "$sbindir" = '${exec_prefix}/sbin' -a \
+    "$datadir" = '${prefix}/share' -a "$libdir" = '${exec_prefix}/lib' -a \
+    "$libexecdir" = '${exec_prefix}/libexec' -a "$sysconfdir" = '${prefix}/etc'
+    then
+    br_cv_valid_prefixes=yes
+    else
+    br_cv_valid_prefixes=no
+    fi
+
+fi
+echo "$as_me:$LINENO: result: $br_cv_valid_prefixes" >&5
+echo "${ECHO_T}$br_cv_valid_prefixes" >&6
+
+  echo "$as_me:$LINENO: checking whether binary relocation is working" >&5
+echo $ECHO_N "checking whether binary relocation is working... $ECHO_C" >&6
+if test "${br_cv_binreloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "x$br_cv_valid_prefixes" = "xyes" -a \
+    "x$ac_cv_file__proc_self_maps" = "xyes"; then
+    br_cv_binreloc=yes
+    else
+    br_cv_binreloc=no
+    fi
+
+fi
+echo "$as_me:$LINENO: result: $br_cv_binreloc" >&5
+echo "${ECHO_T}$br_cv_binreloc" >&6
+
+  if test "x$br_cv_binreloc" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_BINRELOC 1
+_ACEOF
+
+  fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define BR_PTHREAD 0
+_ACEOF
+
+
+
+
+pkg_modules="gtk+-2.0 >= 2.2.0 gdk-2.0 gdk-pixbuf-xlib-2.0"
 
   succeeded=no
 
@@ -19697,7 +19771,7 @@ echo "$as_me: error: Library requirements ($pkg_modules) not met; consider adjus
 
 
 
-                              ac_config_files="$ac_config_files Makefile src/Makefile lib/Makefile"
+                                        ac_config_files="$ac_config_files Makefile src/Makefile lib/Makefile autopackage/default.apspec"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20236,6 +20310,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "lib/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/Makefile" ;;
+  "autopackage/default.apspec" ) CONFIG_FILES="$CONFIG_FILES autopackage/default.apspec" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -20987,18 +21062,37 @@ fi
 if test x"$_HAVE_LD_PRELOAD" = x"no"; then
   { echo "$as_me:$LINENO: WARNING: " >&5
 echo "$as_me: WARNING: " >&2;}
-  { echo "$as_me:$LINENO: WARNING: *** Function preload check failed ! ***" >&5
-echo "$as_me: WARNING: *** Function preload check failed ! ***" >&2;}
-  { echo "$as_me:$LINENO: WARNING: If this is a linux box, please report" >&5
-echo "$as_me: WARNING: If this is a linux box, please report" >&2;}
-  { echo "$as_me:$LINENO: WARNING: this to email@jochen-baier.de;" >&5
-echo "$as_me: WARNING: this to email@jochen-baier.de;" >&2;}
-  { echo "$as_me:$LINENO: WARNING: else please try to fix it and let me know." >&5
-echo "$as_me: WARNING: else please try to fix it and let me know." >&2;}
+  { echo "$as_me:$LINENO: WARNING:      Function preload check failed!" >&5
+echo "$as_me: WARNING:      Function preload check failed!" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      If this is a linux box, please report" >&5
+echo "$as_me: WARNING:      If this is a linux box, please report" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      this to email@jochen-baier.de;" >&5
+echo "$as_me: WARNING:      this to email@jochen-baier.de;" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      else please try to fix it and let me know." >&5
+echo "$as_me: WARNING:      else please try to fix it and let me know." >&2;}
   { echo "$as_me:$LINENO: WARNING: " >&5
 echo "$as_me: WARNING: " >&2;}
-  { echo "$as_me:$LINENO: WARNING: *** Alltray will work with limited features ***" >&5
-echo "$as_me: WARNING: *** Alltray will work with limited features ***" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      Alltray will work with limited features. (or not at all)" >&5
+echo "$as_me: WARNING:      Alltray will work with limited features. (or not at all)" >&2;}
+  { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+fi
+
+if test "x$br_cv_binreloc" = "xno"; then
+  { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+  { echo "$as_me:$LINENO: WARNING:      Binary relocation is not working!" >&5
+echo "$as_me: WARNING:      Binary relocation is not working!" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      If this is a linux box, please report" >&5
+echo "$as_me: WARNING:      If this is a linux box, please report" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      this to email@jochen-baier.de;" >&5
+echo "$as_me: WARNING:      this to email@jochen-baier.de;" >&2;}
+  { echo "$as_me:$LINENO: WARNING:      else please try to fix it and let me know." >&5
+echo "$as_me: WARNING:      else please try to fix it and let me know." >&2;}
+  { echo "$as_me:$LINENO: WARNING: " >&5
+echo "$as_me: WARNING: " >&2;}
+  { echo "$as_me:$LINENO: WARNING:      Alltray will work with limited features. (or not at all)" >&5
+echo "$as_me: WARNING:      Alltray will work with limited features. (or not at all)" >&2;}
   { echo "$as_me:$LINENO: WARNING: " >&5
 echo "$as_me: WARNING: " >&2;}
 fi
